[package]
name = "stdlib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.17"
merkletree = "0.23.0"
substring = "1.4.5"
threadpool = "1.8.1"

[profile.release]
# panic = 'abort'